plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\potla\\Desktop\\ThanqYou-Project\\flutter_application_1\\build\\web"
publishOrigin = "default"
base = "C:\\Users\\potla\\Desktop\\ThanqYou-Project\\flutter_application_1\\build\\web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]